version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app/frontend
      - ./shared:/app/shared
      - frontend_node_modules:/app/node_modules
      - frontend_dist:/app/frontend/.nuxt
    environment:
      - NUXT_HOST=0.0.0.0
      - NUXT_PORT=3000
      - BACKEND_URL=http://backend:3000
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile.dev
    ports:
      - "3001:3000"
    volumes:
      - ./backend:/app/backend
      - ./shared:/app/shared
      - backend_node_modules:/app/node_modules
    environment:
      - PORT=3000
      - NODE_ENV=development

volumes:
  frontend_node_modules:
  frontend_dist:
  backend_node_modules: 